#!/usr/bin/env python3
"""
Batch convert all JSON files in json_test/ to nuCAD Python files in nucad_test/

Usage:
    python batch_convert.py
"""
import json
from pathlib import Path
from json_to_nucad.converter import ModularJSONToNuCADConverter


def generate_nucad_code(actions: list, stl_filename: str, headless: bool = True) -> str:
    """Generate Python code for running the actions"""
    code_template = '''# Generated by JSON to nuCAD converter
import sys, os
# Add parent directory to path so we can import nuCAD
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions, headless={headless}):
    env = nuCADEnv(viz=not headless, render_setting={{"show_axes": True}})
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        if not headless:
            print(f'Step {{i}}: {{type(action).__name__}}')
        
    if not headless:
        env.render()
        env.renderer.show_final_shape()
    return env, obs

actions = {actions_list}

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--headless', action='store_true', default=True, help='Run without UI (default)')
    parser.add_argument('--show-ui', action='store_true', help='Show the visualization UI')
    args = parser.parse_args()
    
    headless = not args.show_ui
    env, obs = run(actions, headless=headless)
    # Export to stl_test directory
    stl_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'stl_test', '{stl_filename}')
    os.makedirs(os.path.dirname(stl_path), exist_ok=True)
    env.export(type='stl', filename=stl_path)
    if not headless:
        print(f'Exported STL to: {{stl_path}}.stl')
'''
    
    # Format actions as Python code
    actions_str = "[\n"
    for action in actions:
        actions_str += f"    {repr(action)},\n"
    actions_str += "]"
    
    return code_template.format(actions_list=actions_str, stl_filename=stl_filename, headless=headless)


def main():
    # Set up directories
    json_dir = Path("json_test")
    output_dir = Path("nucad_test")
    stl_dir = Path("stl_test")
    
    # Create output directories if they don't exist
    output_dir.mkdir(exist_ok=True)
    stl_dir.mkdir(exist_ok=True)
    
    # Get all JSON files
    json_files = list(json_dir.glob("*.json"))
    
    if not json_files:
        print(f"No JSON files found in {json_dir}/")
        return
    
    print(f"Found {len(json_files)} JSON file(s) to convert\n")
    
    # Initialize converter
    converter = ModularJSONToNuCADConverter()
    
    # Convert each JSON file
    for json_file in json_files:
        print(f"Converting: {json_file.name}")
        
        try:
            # Read JSON
            with open(json_file, 'r') as f:
                json_data = json.load(f)
            
            # Convert to actions
            actions = converter.convert_json_to_actions(json_data)
            
            # Generate Python code with STL filename (headless mode)
            code = generate_nucad_code(actions, json_file.stem, headless=True)
            
            # Write output file
            output_file = output_dir / f"{json_file.stem}.py"
            with open(output_file, 'w') as f:
                f.write(code)
            
            print(f"  ✓ Generated {len(actions)} actions → {output_file}")
            
            # Run the generated script silently to create STL
            print(f"  ⏳ Building 3D model and exporting STL...")
            import subprocess
            result = subprocess.run(
                ['python', str(output_file)],
                capture_output=True,
                text=True,
                timeout=60  # 60 second timeout per model
            )
            
            if result.returncode == 0:
                stl_file = stl_dir / f"{json_file.stem}.stl"
                print(f"  ✓ Exported STL → {stl_file}")
            else:
                print(f"  ✗ STL export failed: {result.stderr[:200]}")
            
        except subprocess.TimeoutExpired:
            print(f"  ✗ Timeout: Model took too long to build")
        except Exception as e:
            print(f"  ✗ Error: {e}")
        
        print()
    
    print(f"Batch conversion complete! Output files in {output_dir}/")


if __name__ == "__main__":
    main()
