#!/usr/bin/env python3
"""
Modular JSON to nuCAD Actions Converter - CLI Entry Point

Usage:
    python -m json_to_nucad <json_file_path> [--output <output_file>] [--run]
"""
import argparse
import json
import sys
import os
from pathlib import Path

from .converter import ModularJSONToNuCADConverter


def generate_code(actions: list, output_file: str = None) -> str:
    """Generate Python code for running the actions"""
    code_template = '''# Generated by Modular JSON to nuCAD converter
import sys, os
# Add parent directory to path so we can import nuCAD
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={{"show_axes": True}})
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {{i}}: {{type(action).__name__}}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = {actions_list}

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
'''
    
    # Format actions as Python code
    actions_str = "[\n"
    for action in actions:
        actions_str += f"    {repr(action)},\n"
    actions_str += "]"
    
    code = code_template.format(actions_list=actions_str)
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(code)
        print(f"Generated code saved to: {output_file}")
    
    return code


def main():
    parser = argparse.ArgumentParser(description="Convert JSON CAD data to nuCAD actions (Modular)")
    parser.add_argument("json_file", help="Path to JSON file containing CAD data")
    parser.add_argument("--output", "-o", help="Output Python file path")
    parser.add_argument("--run", action="store_true", help="Run the generated actions immediately")
    parser.add_argument("--stats", action="store_true", help="Show conversion statistics")
    
    args = parser.parse_args()
    
    # Read JSON file
    try:
        with open(args.json_file, 'r') as f:
            json_data = json.load(f)
    except FileNotFoundError:
        print(f"Error: File '{args.json_file}' not found")
        return 1
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in '{args.json_file}': {e}")
        return 1
    
    # Convert to actions
    converter = ModularJSONToNuCADConverter()
    actions = converter.convert_json_to_actions(json_data)
    
    print(f"Generated {len(actions)} actions")
    
    # Show stats if requested
    if args.stats:
        stats = converter.get_conversion_stats()
        print("\nConversion Statistics:")
        for key, value in stats.items():
            if key != "operation_history":  # Skip detailed history for now
                print(f"  {key}: {value}")
    
    # Generate output file name if not provided
    if not args.output:
        input_path = Path(args.json_file)
        args.output = f"generated_actions_{input_path.stem}.py"
    
    # Generate code
    code = generate_code(actions, args.output)
    
    if args.run:
        print("\nRunning generated actions...")
        # Execute the generated code
        exec_globals = {}
        exec(code, exec_globals)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())