# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True})
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-1.5, 3.5), end=(-11.0, 3.5)),
    AddArc(p1=(-11.0, 3.5), p2=(-12.414213562373096, 2.914213562373095), p3=(-13.0, 1.4999999999999998)),
    AddLine(start=(-13.0, 1.5), end=(-13.0, -4.0)),
    AddArc(p1=(-13.0, -4.000000000000001), p2=(-11.82842712474619, -6.82842712474619), p3=(-9.0, -8.0)),
    AddLine(start=(-9.0, -8.0), end=(9.0, -8.0)),
    AddArc(p1=(9.0, -8.0), p2=(11.82842712474619, -6.82842712474619), p3=(13.0, -4.0)),
    AddLine(start=(13.0, -4.0), end=(13.0, 2.0)),
    AddArc(p1=(13.0, 2.0), p2=(12.414213562373096, 3.414213562373095), p3=(11.0, 4.0)),
    AddLine(start=(11.0, 4.0), end=(7.0, 4.0)),
    AddArc(p1=(7.000000000000016, 4.0), p2=(2.7573465914816104, 3.6251079448127967), p3=(-1.4999999999999956, 3.5)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-7.0, -0.0), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(7.0, -0.0), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=4.0, faces=['f2'], direction='one', opposite_height=None),
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(3.0, 0.0), end=(-8.0, 0.0)),
    AddLine(start=(-8.0, 0.0), end=(-8.0, 20.0)),
    AddArc(p1=(-8.0, 20.0), p2=(-6.82842712474619, 22.82842712474619), p3=(-4.000000000000001, 24.0)),
    AddLine(start=(-4.0, 24.0), end=(-1.0, 24.0)),
    AddArc(p1=(-1.0000000000000007, 24.0), p2=(1.8284271247461898, 22.82842712474619), p3=(3.0, 20.0)),
    AddLine(start=(3.0, 20.0), end=(3.0, 0.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-2.5, 19.5), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-2.5, 13.5), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=1.5, faces=['f5'], direction='symmetric', opposite_height=None),
    AddSketch(origin=None, normal=None, on_face='s1:2'),
    StartLoop(),
    AddLine(start=(-9.0, 4.0), end=(-1.5, 10.0)),
    AddLine(start=(-1.5, 10.0), end=(1.5, 10.0)),
    AddLine(start=(1.5, 10.0), end=(9.0, 4.0)),
    AddLine(start=(9.0, 4.0), end=(-9.0, 4.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=-4.0, faces=['f6'], direction='one', opposite_height=None),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
