# Generated by JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddCircle(center=(0.0, 0.0), radius=63.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(0.0, 0.0), radius=38.1),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f1']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(42.07, 17.41), end=(54.26, 17.41)),
    AddLine(start=(54.26, 17.41), end=(54.26, 0.0)),
    AddLine(start=(54.26, 0.0), end=(42.07, 0.0)),
    AddLine(start=(42.07, 0.0), end=(42.07, 17.41)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=0.0, faces=['f2']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-30.66, -46.84), end=(-30.66, -30.18)),
    AddLine(start=(-30.66, -30.18), end=(-45.08, -38.51)),
    AddLine(start=(-45.08, -38.51), end=(-30.66, -46.84)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddLine(start=(-38.63, 32.18), end=(-38.92, 50.17)),
    AddLine(start=(-38.92, 50.17), end=(-25.23, 43.4)),
    AddLine(start=(-25.23, 43.4), end=(-30.1, 33.57)),
    AddLine(start=(-30.1, 33.57), end=(-38.63, 32.18)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=0.0, faces=['f4']),
    Extrude(height=0.0, faces=['f4']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')