# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddCircle(center=(0.0, 0.0), radius=40.91),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f0']),
    AddSketch(origin=None, normal=None, on_face='s0:0'),
    StartLoop(),
    AddLine(start=(-10.73, -17.95), end=(6.62, -17.95)),
    AddLine(start=(6.62, -17.95), end=(6.62, 12.99)),
    AddLine(start=(6.62, 12.99), end=(-10.73, 12.99)),
    AddLine(start=(-10.73, 12.99), end=(-10.73, -17.95)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=73.91, faces=['f1']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
