# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True}, orient_policy='positive')
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-0.0, 15.03), end=(-0.0, 10.24)),
    AddSpline(points=[(0.0, 10.24), (3.19, 9.84), (5.37, 8.29), (6.7, 4.42), (8.39, -1.63), (10.08, -6.81), (12.62, -12.08), (16.29, -15.15), (20.26, -16.87), (28.24, -18.46), (36.41, -19.06), (44.27, -19.12), (53.21, -18.52), (57.17, -16.99), (60.3, -14.15), (62.79, -9.12), (65.48, -1.46), (67.22, 3.56), (68.4, 4.08), (72.83, 3.97), (73.23, 5.16), (73.37, 12.56), (73.31, 13.47), (70.52, 14.25), (63.28, 16.33), (56.14, 17.97), (46.83, 19.71), (35.39, 20.71)]),
    AddSpline(points=[(35.39, 20.71), (25.12, 20.44), (14.65, 18.41), (7.75, 16.14), (2.22, 15.08), (-0.0, 15.03)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=2.0, faces=['f0']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    Extrude(height=2.0, faces=['f0']),
    Extrude(height=1.0, faces=['f0']),
    AddSketch(origin=None, normal=None, on_face='s2:1'),
    StartLoop(),
    AddLine(start=(67.96, 10.25), end=(71.71, 10.25)),
    AddLine(start=(71.71, 10.25), end=(71.71, 6.25)),
    AddLine(start=(71.71, 6.25), end=(67.96, 6.25)),
    AddLine(start=(67.96, 6.25), end=(67.96, 10.25)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=1.0, faces=['f1']),
    AddSketch(origin=None, normal=None, on_face='s2:1'),
    StartLoop(),
    AddLine(start=(73.2, 13.55), end=(71.16, 13.55)),
    AddLine(start=(71.16, 13.55), end=(71.16, 3.9)),
    AddLine(start=(71.16, 3.9), end=(73.2, 3.9)),
    AddLine(start=(73.2, 3.9), end=(73.2, 13.55)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=2.1, faces=['f2']),
    AddSketch(origin=None, normal=None, on_face='s3:1'),
    StartLoop(),
    AddLine(start=(62.42, 10.25), end=(66.72, 10.25)),
    AddLine(start=(66.72, 10.25), end=(66.72, 6.25)),
    AddLine(start=(66.72, 6.25), end=(62.42, 6.25)),
    AddLine(start=(62.42, 6.25), end=(62.42, 10.25)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=5.5, faces=['f3']),
    AddSketch(origin=None, normal=None, on_face='s5:2'),
    AddSketch(origin=None, normal=None, on_face='s4:1'),
    StartLoop(),
    AddLine(start=(9.77, -5.91), end=(11.87, -5.91)),
    AddSpline(points=[(11.87, -5.91), (9.19, 3.9), (8.93, 8.54)]),
    AddLine(start=(8.93, 8.54), end=(4.55, 9.16)),
    AddSpline(points=[(4.55, 9.16), (5.95, 7.12), (6.95, 3.46), (8.34, -1.47), (9.77, -5.91)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=5.0, faces=['f4']),
    AddSketch(origin=None, normal=None, on_face='s6:1'),
    StartLoop(),
    AddCircle(center=(8.13, 11.64), radius=2.28),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(63.64, 11.64), radius=2.28),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(16.36, -13.45), radius=1.3),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(59.15, -13.45), radius=1.3),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=0.5, faces=['f8']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
