# Generated by JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(73.2, 13.55), end=(71.16, 13.55)),
    AddLine(start=(71.16, 13.55), end=(71.16, 3.9)),
    AddLine(start=(71.16, 3.9), end=(73.2, 3.9)),
    AddLine(start=(73.2, 3.9), end=(73.2, 13.55)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=2.1, faces=['f0']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(62.42, 10.25), end=(66.72, 10.25)),
    AddLine(start=(66.72, 10.25), end=(66.72, 6.25)),
    AddLine(start=(66.72, 6.25), end=(62.42, 6.25)),
    AddLine(start=(62.42, 6.25), end=(62.42, 10.25)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=5.5, faces=['f1']),
    Fillet(edge='e0', radius=0.0, solid='s1'),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    Fillet(edge='e0', radius=1.0, solid='s2'),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(9.77, -5.91), end=(11.87, -5.91)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddLine(start=(8.93, 8.54), end=(4.55, 9.16)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddSpline(points=[(0.0, 10000.0), (4.55, 9.16), (5.95, 7.12), (6.95, 3.46), (8.34, -1.47), (9.77, -5.91), (7.76, -9.34), (4.99, -15.93), (5.06, 8.54), (9.31, -4.47), (0.0, 1000.0)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddSpline(points=[(0.0, 6000.0), (8.93, 8.54), (9.19, 3.9), (11.87, -5.91), (-0.13, -10.5), (5.61, -17.85), (8.91, 7.13), (10.75, -2.36), (0.0, 1000.0)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-0.0, 15.03), end=(-0.0, 10.24)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddSpline(points=[(0.0, 56000.0), (35.39, 20.71), (46.83, 19.71), (56.14, 17.97), (63.28, 16.33), (70.52, 14.25), (73.31, 13.47), (73.37, 12.56), (73.23, 5.16), (72.83, 3.97), (68.4, 4.08), (67.22, 3.56), (65.48, -1.46), (62.79, -9.12), (60.3, -14.15), (57.17, -16.99), (53.21, -18.52), (44.27, -19.12), (36.41, -19.06), (28.24, -18.46), (20.26, -16.87), (16.29, -15.15), (12.62, -12.08), (10.08, -6.81), (8.39, -1.63), (6.7, 4.42), (5.37, 8.29), (3.19, 9.84), (0.0, 10.24), (372.96, -25.46), (-114.35, -3.97), (42.21, 20.25), (1.11, 10.28), (0.0, 1000.0)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddSpline(points=[(0.0, 12000.0), (35.39, 20.71), (25.12, 20.44), (14.65, 18.41), (7.75, 16.14), (2.22, 15.08), (-0.0, 15.03), (-67.21, -0.11), (-16.93, 0.35), (29.88, 20.71), (0.64, 15.02), (0.0, 1000.0)]),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=5.0, faces=['f8']),
    Fillet(edge='e0', radius=7.0, solid='s4'),
    Fillet(edge='e0', radius=2.0, solid='s5'),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddCircle(center=(8.13, 11.64), radius=2.28),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(63.64, 11.64), radius=2.28),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(16.36, -13.45), radius=1.3),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(59.15, -13.45), radius=1.3),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=0.5, faces=['f12']),
    Fillet(edge='e0', radius=3.0, solid='s7'),
    Chamfer(edge='e0', distance=1.27, solid='s8'),
    Fillet(edge='e0', radius=0.3, solid='s9'),
    Extrude(height=2.0, faces=['f12']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    Extrude(height=2.0, faces=['f12']),
    Extrude(height=1.0, faces=['f12']),
    Fillet(edge='e0', radius=1.0, solid='s13'),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(67.96, 10.25), end=(71.71, 10.25)),
    AddLine(start=(71.71, 10.25), end=(71.71, 6.25)),
    AddLine(start=(71.71, 6.25), end=(67.96, 6.25)),
    AddLine(start=(67.96, 6.25), end=(67.96, 10.25)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=1.0, faces=['f13']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')