# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(29.86, -29.32), end=(-26.45, -29.32)),
    AddLine(start=(-26.45, -29.32), end=(-0.0, 29.34)),
    AddLine(start=(-0.0, 29.34), end=(29.86, -29.32)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=60.96, faces=['f0']),
    AddSketch(origin=None, normal=None, on_face='s0:2'),
    StartLoop(),
    AddCircle(center=(-22.71, 5.43), radius=12.27),
    CloseProfile(),
    MakeFace(operation='cut'),
    AddSketch(origin=None, normal=None, on_face='s0:2'),
    StartLoop(),
    AddLine(start=(3.25, -16.81), end=(3.25, 0.0)),
    AddLine(start=(3.25, 0.0), end=(-3.4, 0.0)),
    AddLine(start=(-3.4, 0.0), end=(-3.4, -16.81)),
    AddLine(start=(-3.4, -16.81), end=(3.25, -16.81)),
    CloseProfile(),
    MakeFace(operation='cut'),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
