# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True}, orient_policy='positive')
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 1, 0), on_face=None),
    StartLoop(),
    AddCircle(center=(-13.16, 5.28), radius=13.82),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f0']),
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(-18.1, -24.07), end=(0.0, -24.07)),
    AddLine(start=(0.0, -24.07), end=(0.0, -40.7)),
    AddLine(start=(0.0, -40.7), end=(-18.1, -40.7)),
    AddLine(start=(-18.1, -40.7), end=(-18.1, -24.07)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f1']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-67.0, -31.25), end=(-16.56, -31.25)),
    AddLine(start=(-16.56, -31.25), end=(-16.56, -39.33)),
    AddLine(start=(-16.56, -39.33), end=(-67.0, -39.33)),
    AddLine(start=(-67.0, -39.33), end=(-67.0, -31.25)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f2']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
