# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(10.16, 9.0), end=(10.16, -11.96)),
    AddLine(start=(10.16, -11.96), end=(-12.27, -11.96)),
    AddLine(start=(-12.27, -11.96), end=(-12.27, 9.0)),
    AddLine(start=(-12.27, 9.0), end=(10.16, 9.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=22.61, faces=['f0']),
    Extrude(height=216.15, faces=['f0']),
    AddSketch(origin=None, normal=None, on_face='s1:2'),
    StartLoop(),
    AddCircle(center=(-9.47, 3.39), radius=6.15),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=91.19, faces=['f1']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
