# Generated by JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True)
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        if env.viz:
            env.render()
    
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(-15.31, -13.03), end=(-38.16, 29.56)),
    AddLine(start=(-38.16, 29.56), end=(-10.54, 29.56)),
    AddLine(start=(-10.54, 29.56), end=(16.08, 9.28)),
    AddLine(start=(16.08, 9.28), end=(11.63, -24.66)),
    AddLine(start=(11.63, -24.66), end=(-15.31, -13.03)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f0']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddCircle(center=(-0.65, 0.55), radius=4.51),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f1']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')