# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True}, orient_policy='positive')
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(0.0, 30.48), end=(0.0, -30.48)),
    AddLine(start=(0.0, -30.48), end=(28.45, -30.48)),
    AddLine(start=(28.45, -30.48), end=(28.45, 30.48)),
    AddLine(start=(28.45, 30.48), end=(0.0, 30.48)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=48.26, faces=['f0']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(28.45, 0.0), end=(119.38, 0.0)),
    AddLine(start=(119.38, 0.0), end=(88.58, -17.78)),
    AddLine(start=(88.58, -17.78), end=(28.45, -17.78)),
    AddLine(start=(28.45, -17.78), end=(28.45, -0.0)),
    AddLine(start=(28.45, 0.0), end=(28.45, 17.78)),
    AddLine(start=(28.45, 17.78), end=(88.58, 17.78)),
    AddLine(start=(88.58, 17.78), end=(119.38, -0.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddLine(start=(119.38, -0.0), end=(88.58, 17.78)),
    AddLine(start=(88.58, 17.78), end=(28.45, 17.78)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=28.45, faces=['f2']),
    AddSketch(origin=(0, 0, 0), normal=(0, 1, 0), on_face=None),
    StartLoop(),
    AddLine(start=(119.38, 28.45), end=(100.08, 28.45)),
    AddLine(start=(100.08, 28.45), end=(100.08, 17.27)),
    AddLine(start=(100.08, 17.27), end=(119.38, 17.27)),
    AddLine(start=(119.38, 17.27), end=(119.38, 28.45)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(63.5, 14.22), radius=6.35),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f4']),
    Extrude(height=25.4, faces=['f4']),
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddLine(start=(0.0, 17.78), end=(0.0, -17.78)),
    AddLine(start=(0.0, -17.78), end=(10.16, -17.78)),
    AddLine(start=(10.16, -17.78), end=(10.16, 17.78)),
    AddLine(start=(10.16, 17.78), end=(0.0, 17.78)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f5']),
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(12.7, 48.26), end=(-12.7, 48.26)),
    AddLine(start=(-12.7, 48.26), end=(-12.7, 38.1)),
    AddLine(start=(-12.7, 38.1), end=(12.7, 38.1)),
    AddLine(start=(12.7, 38.1), end=(12.7, 48.26)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f6']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
