# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True}, orient_policy='positive')
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 0, 1), on_face=None),
    StartLoop(),
    AddArc(p1=(-0.03999999999999989, 0.08999999999999986), p2=(0.06804852039070572, 0.09317515335800741), p3=(0.1757241379310349, 0.10268965517241369)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(-0.33, -0.10000000000000002), p2=(-0.30071067811865476, -0.17071067811865476), p3=(-0.23, -0.2)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(0.23, -0.2), p2=(0.30071067811865476, -0.17071067811865476), p3=(0.33, -0.1)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(-0.28, 0.09), p2=(-0.3153553390593274, 0.07535533905932737), p3=(-0.33, 0.039999999999999994)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(0.33, 0.05), p2=(0.3153553390593274, 0.08535533905932738), p3=(0.28, 0.1)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-7.0, -0.0), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(7.0, -0.0), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=4.0, faces=['f6']),
    AddSketch(origin=(0, 0, 0), normal=(1, 0, 0), on_face=None),
    StartLoop(),
    AddLine(start=(3.0, 0.0), end=(-8.0, 0.0)),
    AddLine(start=(-8.0, 0.0), end=(-8.0, 20.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(-0.10000000000000002, 0.61), p2=(-0.17071067811865476, 0.5807106781186547), p3=(-0.2, 0.51)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddArc(p1=(0.07, 0.51), p2=(0.04071067811865475, 0.5807106781186547), p3=(-0.030000000000000016, 0.61)),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-2.5, 19.5), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    StartLoop(),
    AddCircle(center=(-2.5, 13.5), radius=1.5),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=3.0, faces=['f11']),
    AddSketch(origin=None, normal=None, on_face='s1:2'),
    StartLoop(),
    AddLine(start=(-9.0, 4.0), end=(-1.5, 10.0)),
    AddLine(start=(-1.5, 10.0), end=(1.5, 10.0)),
    AddLine(start=(1.5, 10.0), end=(9.0, 4.0)),
    AddLine(start=(9.0, 4.0), end=(-9.0, 4.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=4.0, faces=['f12']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
