# Generated by Modular JSON to nuCAD converter
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from nuCAD.env.base_env import nuCADEnv
from nuCAD.env.actions import (
    AddSketch, StartLoop, AddLine, AddArc, AddCircle, AddEllipse,
    AddBezier, AddSpline, AddSweep,
    SubtractWires, CloseProfile, MakeFace, Extrude, Boolean,
    Fillet, Chamfer, Revolve, Loft, Shell, Mirror, Transform,
    LinearPattern, CircularPattern
)

def run(actions):
    env = nuCADEnv(viz=True, render_setting={"show_axes": True}, orient_policy='positive')
    env.reset()
    
    for i, action in enumerate(actions):
        obs, reward, done, info = env.step(action)
        print(f'Step {i}: {type(action).__name__}')
        
    env.render()
    env.renderer.show_final_shape()
    return env, obs

actions = [
    AddSketch(origin=(0, 0, 0), normal=(0, 1, 0), on_face=None),
    StartLoop(),
    AddLine(start=(0.0, 0.0), end=(0.0, 54.71)),
    AddLine(start=(0.0, 54.71), end=(21.95, 0.0)),
    AddLine(start=(21.95, 0.0), end=(0.0, 0.0)),
    CloseProfile(),
    MakeFace(operation='cut'),
    Extrude(height=25.4, faces=['f0']),
]

if __name__ == '__main__':
    env, obs = run(actions)
    env.export(type='stl', filename='generated_model')
